DROP SEQUENCE RESERVATIONSEQ;
DROP TABLE RESERVATIONBOARD;

CREATE SEQUENCE RESERVATIONSEQ;
CREATE TABLE RESERVATIONBOARD(

	RESERVATIONSEQ		NUMBER			PRIMARY KEY,
	USERSEQ				NUMBER			NOT NULL,
	PRODUCTSEQ			NUMBER			NOT NULL,
	PRICE				NUMBER			NOT NULL,
	PAYCONTENT			VARCHAR2(1000)	NOT NULL,
	PAYDATE				DATE			NOT NULL,
	COUPONSEQ			NUMBER

);


